# Generated by Django 5.1.5 on 2025-02-02 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpoint',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainnings.participation'),
        ),
        migrations.AlterField(
            model_name='missingpointrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='missing_proofs/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m'),
        ),
    ]
