# Generated by Django 5.1.5 on 2025-02-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='faculty',
        ),
    ]
