# Generated by Django 5.1.5 on 2025-01-23 17:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0002_activity_studentparticipation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name_activity',
            new_name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='criteria',
            field=models.CharField(choices=[('1', 'Criteria 1'), ('2', 'Criteria 2'), ('3', 'Criteria 3'), ('4', 'Criteria 4'), ('5', 'Criteria 5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('is_attended', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='proofs/%Y/%m')),
                ('verified', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainnings.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentParticipation',
        ),
    ]
