# Generated by Django 5.1.5 on 2025-02-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0002_trainingpoint_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpoint',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainnings.faculty'),
        ),
    ]
