# Generated by Django 5.1.5 on 2025-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0003_rename_name_activity_activity_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='achievement',
            field=models.CharField(blank=True, choices=[('1', 'Excellent'), ('2', 'Good'), ('3', 'Average'), ('4', 'Below average'), ('5', 'Weak')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='class_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='faculty',
            field=models.CharField(blank=True, choices=[('1', 'Technology'), ('2', 'Law'), ('3', 'English language'), ('4', 'Tourist'), ('5', 'Hotel management')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
