# Generated by Django 5.1.5 on 2025-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0004_participation_achievement_participation_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='participation',
            name='achievement',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BELOW AVERAGE', 'Below average'), ('WEAK', 'Weak')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='faculty',
            field=models.CharField(blank=True, choices=[('TE', 'Technology'), ('LA', 'Law'), ('EL', 'English language'), ('TOUR', 'Tourist'), ('HOM', 'Hotel management')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tags',
            field=models.ManyToManyField(to='trainnings.tag'),
        ),
    ]
