# Generated by Django 5.1.5 on 2025-02-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0004_remove_trainingpoint_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpoint',
            name='achievement',
        ),
    ]
