# Generated by Django 5.1.5 on 2025-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0005_tag_alter_participation_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(to='trainnings.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('assistant', 'Student Assistant'), ('admin', 'CTSV')], default='student', max_length=20),
        ),
    ]
