# Generated by Django 5.1.5 on 2025-02-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0006_remove_trainingpoint_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpoint',
            name='activity',
        ),
    ]
