# Generated by Django 5.1.5 on 2025-01-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainnings', '0006_remove_participation_tags_activity_tags_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
